version: "3.8"
services:
  investimentos:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/bash -c "poetry run python main.py"
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
