version: "3.8"
services:
  investimentos:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URI=mongodb://mongodb:27017/investimentos
    command: /bin/bash -c "poetry run python -m debugpy --listen 0.0.0.0:5678 main.py"
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27019:27019"
    volumes:
      - mongodb-data:/data/db # Persiste os dados do MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # Configurações iniciais (opcional)
      - MONGO_INITDB_ROOT_PASSWORD=example # Configurações iniciais (opcional)
volumes:
  mongodb-data: # Define o volume para persistência de dados
    name: mongodb-data
